import { Product, ABCClass, StockStatus } from './types';

// Helper to generate mock transactions
const generateTransactions = (count: number): any[] => {
  const transactions = [];
  const types = ['IN', 'OUT', 'ADJUSTMENT'];
  for (let i = 0; i < count; i++) {
    transactions.push({
      id: `trx-${Math.random().toString(36).substr(2, 9)}`,
      date: new Date(Date.now() - Math.floor(Math.random() * 90) * 86400000).toISOString(),
      type: types[Math.floor(Math.random() * types.length)],
      quantity: Math.floor(Math.random() * 50) + 1,
      note: 'System generated',
    });
  }
  return transactions.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    sku: 'EL-001',
    name: 'Industrial Motor 500W',
    category: 'Electronics',
    description: 'High efficiency brushless DC motor for conveyor belts.',
    stockLevel: 12,
    safetyStock: 10,
    reorderPoint: 15,
    unitCost: 150.00,
    unitPrice: 280.00,
    leadTimeDays: 14,
    demandRate: 1.2,
    holdingCostPercent: 0.2,
    orderingCost: 50,
    supplier: 'TechMotors Inc.',
    location: 'A-12-04',
    lastCountDate: '2023-10-15',
    transactions: generateTransactions(10),
  },
  {
    id: 'p2',
    sku: 'EL-002',
    name: 'Control Panel V2',
    category: 'Electronics',
    description: 'Main interface board for industrial automation.',
    stockLevel: 45,
    safetyStock: 5,
    reorderPoint: 10,
    unitCost: 85.00,
    unitPrice: 195.00,
    leadTimeDays: 7,
    demandRate: 0.8,
    holdingCostPercent: 0.15,
    orderingCost: 30,
    supplier: 'CircuitPros',
    location: 'A-12-05',
    lastCountDate: '2023-11-01',
    transactions: generateTransactions(5),
  },
  {
    id: 'p3',
    sku: 'ME-105',
    name: 'Steel Bearing 50mm',
    category: 'Mechanical',
    description: 'Stainless steel ball bearing, sealed.',
    stockLevel: 400,
    safetyStock: 100,
    reorderPoint: 150,
    unitCost: 2.50,
    unitPrice: 8.00,
    leadTimeDays: 3,
    demandRate: 15,
    holdingCostPercent: 0.1,
    orderingCost: 15,
    supplier: 'SteelWorks',
    location: 'B-03-01',
    lastCountDate: '2023-09-20',
    transactions: generateTransactions(25),
  },
  {
    id: 'p4',
    sku: 'ME-106',
    name: 'Hydraulic Pump Gen3',
    category: 'Mechanical',
    description: 'Heavy duty hydraulic pump for lifting mechanisms.',
    stockLevel: 3,
    safetyStock: 5,
    reorderPoint: 8,
    unitCost: 450.00,
    unitPrice: 1200.00,
    leadTimeDays: 21,
    demandRate: 0.3,
    holdingCostPercent: 0.25,
    orderingCost: 100,
    supplier: 'HydroFlow',
    location: 'C-01-01',
    lastCountDate: '2023-11-20',
    transactions: generateTransactions(8),
  },
  {
    id: 'p5',
    sku: 'PK-500',
    name: 'Corrugated Box Large',
    category: 'Packaging',
    description: 'Standard large shipping box.',
    stockLevel: 1200,
    safetyStock: 200,
    reorderPoint: 500,
    unitCost: 0.50,
    unitPrice: 0.00, // Internal use
    leadTimeDays: 2,
    demandRate: 50,
    holdingCostPercent: 0.1,
    orderingCost: 20,
    supplier: 'PackItAll',
    location: 'D-01-01',
    lastCountDate: '2023-10-01',
    transactions: generateTransactions(15),
  },
  {
    id: 'p6',
    sku: 'CH-202',
    name: 'Industrial Solvent 5L',
    category: 'Chemicals',
    description: 'Heavy duty cleaning solvent.',
    stockLevel: 18,
    safetyStock: 20,
    reorderPoint: 30,
    unitCost: 25.00,
    unitPrice: 65.00,
    leadTimeDays: 5,
    demandRate: 2,
    holdingCostPercent: 0.2,
    orderingCost: 45,
    supplier: 'ChemCo',
    location: 'H-05-02',
    lastCountDate: '2023-11-10',
    transactions: generateTransactions(12),
  },
  {
    id: 'p7',
    sku: 'EL-005',
    name: 'Sensor Module X1',
    category: 'Electronics',
    description: 'Proximity sensor for automation lines.',
    stockLevel: 85,
    safetyStock: 15,
    reorderPoint: 25,
    unitCost: 12.00,
    unitPrice: 35.00,
    leadTimeDays: 10,
    demandRate: 1.5,
    holdingCostPercent: 0.15,
    orderingCost: 25,
    supplier: 'TechMotors Inc.',
    location: 'A-14-02',
    lastCountDate: '2023-11-05',
    transactions: generateTransactions(20),
  },
  {
    id: 'p8',
    sku: 'ME-299',
    name: 'Titanium Bolt Set',
    category: 'Mechanical',
    description: 'High tensile strength bolt set.',
    stockLevel: 0,
    safetyStock: 50,
    reorderPoint: 100,
    unitCost: 15.00,
    unitPrice: 45.00,
    leadTimeDays: 14,
    demandRate: 5,
    holdingCostPercent: 0.1,
    orderingCost: 35,
    supplier: 'SteelWorks',
    location: 'B-04-12',
    lastCountDate: '2023-10-30',
    transactions: generateTransactions(6),
  },
];
